image: openjdk:8-jdk

variables:
  ANDROID_TARGET_SDK: "19"
  ANDROID_BUILD_TOOLS: "23.0.3"
  ANDROID_SDK_TOOLS: "23.1.0"

before_script:
  - chmod +x ./gradlew

build:
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/